annotations:
  owner: harmonycloud
apiVersion: v2
appVersion: "5.7"
dependencies:
- alias: mysql-operator
  condition: mysql-operator.enabled
  name: mysql-operator
  repository: file://./charts/mysql-operator
  version: 1.2.5-1
description: mysql instance chart
name: mysql
type: application
version: 1.2.5-1
